services:
  app.backend:
    container_name: app.backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - app.db
    volumes:
      - ./backend:/app
    networks:
      - app.network

  app.frontend:
    container_name: app.frontend
    image: nginx:latest
    ports:
      - '4000:80'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - './frontend/dist/frontend/browser:/usr/share/nginx/html'
    networks:
      - app.network

  app.db:
    container_name: app.db
    image: postgres:17
    environment:
      POSTGRES_USER: '${DB_USER_NAME}'
      POSTGRES_PASSWORD: '${DB_USER_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app.network

volumes:
  postgres_data:
    name: postgres_data
    driver: local

networks:
  app.network:
    name: app.network
    driver: bridge
